export const bangladeshDistrictData = [
  {
    zila: "Dhaka",
    upazila: [
      "Dhamrai",
      "Dohar",
      "Keraniganj",
      "Nawabganj",
      "Savar",
      "Tejgaon",
    ],
  },
  {
    zila: "Faridpur",
    upazila: [
      "Alfadanga",
      "Bhanga",
      "Boalmari",
      "Charbhadrasan",
      "Faridpur Sadar",
      "Madhukhali",
      "Nagarkanda",
      "Sadarpur",
      "Saltha",
    ],
  },
  {
    zila: "Gazipur",
    upazila: ["Gazipur Sadar", "Kaliganj", "Kaliakair", "Kapasia", "Sreepur"],
  },
  {
    zila: "Gopalganj",
    upazila: [
      "Gopalganj Sadar",
      "Kashiani",
      "Kotalipara",
      "Muksudpur",
      "Tungipara",
    ],
  },
  {
    zila: "Kishoreganj",
    upazila: [
      "Austagram",
      "Bajitpur",
      "Bhairab",
      "Hossainpur",
      "Itna",
      "Karimganj",
      "Katiadi",
      "Kishoreganj Sadar",
      "Kuliarchar",
      "Mithamain",
      "Nikli",
      "Pakundia",
      "Tarail",
    ],
  },
  {
    zila: "Madaripur",
    upazila: ["Madaripur Sadar", "Kalkini", "Rajoir", "Shibchar"],
  },
  {
    zila: "Manikganj",
    upazila: [
      "Daulatpur",
      "Ghior",
      "Harirampur",
      "Manikganj Sadar",
      "Saturia",
      "Shivalaya",
      "Singair",
    ],
  },
  {
    zila: "Munshiganj",
    upazila: [
      "Gajaria",
      "Lohajang",
      "Munshiganj Sadar",
      "Sirajdikhan",
      "Sreenagar",
      "Tongibari",
    ],
  },
  {
    zila: "Narayanganj",
    upazila: [
      "Araihazar",
      "Bandar",
      "Narayanganj Sadar",
      "Rupganj",
      "Sonargaon",
    ],
  },
  {
    zila: "Narsingdi",
    upazila: [
      "Belabo",
      "Monohardi",
      "Narsingdi Sadar",
      "Palash",
      "Raipura",
      "Shibpur",
    ],
  },
  {
    zila: "Rajbari",
    upazila: [
      "Rajbari Sadar",
      "Goalandaghat",
      "Pangsha",
      "Baliakandi",
      "Kalukhali",
    ],
  },
  {
    zila: "Shariatpur",
    upazila: [
      "Shariatpur Sadar",
      "Damudya",
      "Naria",
      "Gosairhat",
      "Bhedarganj",
      "Janjira",
    ],
  },
  {
    zila: "Tangail",
    upazila: [
      "Basail",
      "Bhuapur",
      "Delduar",
      "Ghatail",
      "Gopalpur",
      "Kaliyapair",
      "Madhupur",
      "Mirzapur",
      "Nagarpur",
      "Sakhipur",
      "Tangail Sadar",
      "Dhanbari",
    ],
  },

  // Chittagong Division
  {
    zila: "Bandarban",
    upazila: [
      "Alikadam",
      "Bandarban Sadar",
      "Lama",
      "Naikhongchhari",
      "Rowangchhari",
      "Ruma",
      "Thanchi",
    ],
  },
  {
    zila: "Brahmanbaria",
    upazila: [
      "Akhaura",
      "Bancharampur",
      "Brahmanbaria Sadar",
      "Kasba",
      "Nabinagar",
      "Nasirnagar",
      "Sarail",
      "Ashuganj",
      "Bijoynagar",
    ],
  },
  {
    zila: "Chandpur",
    upazila: [
      "Chandpur Sadar",
      "Faridganj",
      "Haimchar",
      "Kachua",
      "Matlab Uttar",
      "Matlab Dakshin",
      "Shahrasti",
      "Haziganj",
    ],
  },
  {
    zila: "Chittagong",
    upazila: [
      "Anwara",
      "Banshkhali",
      "Boalkhali",
      "Chandanaish",
      "Fatikchhari",
      "Hathazari",
      "Lohagara",
      "Mirsharai",
      "Patiya",
      "Rangunia",
      "Raozan",
      "Sandwip",
      "Satkania",
      "Sitakunda",
      "Patenga",
      "Halishahar",
    ],
  },
  {
    zila: "Comilla",
    upazila: [
      "Barura",
      "Brahmanpara",
      "Burichong",
      "Chandina",
      "Chauddagram",
      "Daudkandi",
      "Debidwar",
      "Homna",
      "Laksam",
      "Meghna",
      "Muradnagar",
      "Nangalkot",
      "Titas",
      "Monohorganj",
    ],
  },
  {
    zila: "Cox's Bazar",
    upazila: [
      "Chakaria",
      "Cox's Bazar Sadar",
      "Kutubdia",
      "Maheshkhali",
      "Ramu",
      "Teknaf",
      "Ukhia",
      "Pekua",
    ],
  },
  {
    zila: "Feni",
    upazila: [
      "Feni Sadar",
      "Fulgazi",
      "Daganbhuiyan",
      "Parshuram",
      "Sonagazi",
      "Chhagalnaiya",
    ],
  },
  {
    zila: "Khagrachari",
    upazila: [
      "Dighinala",
      "Khagrachari Sadar",
      "Laxmichhari",
      "Manikchhari",
      "Matiranga",
      "Panchhari",
      "Ramgarh",
      "Mahalchhari",
    ],
  },
  {
    zila: "Lakshmipur",
    upazila: ["Lakshmipur Sadar", "Kamalnagar", "Raipur", "Ramganj", "Ramgati"],
  },
  {
    zila: "Noakhali",
    upazila: [
      "Noakhali Sadar",
      "Begumganj",
      "Chatkhil",
      "Senbagh",
      "Companiganj",
      "Hatiya",
      "Sonaimuri",
      "Subarnachar",
      "Kabirhat",
    ],
  },
  {
    zila: "Rangamati",
    upazila: [
      "Baghaichhari",
      "Barkal",
      "Belaichhari",
      "Juraichhari",
      "Kaptai",
      "Kawkhali",
      "Langadu",
      "Naniarchar",
      "Rajasthali",
      "Rangamati Sadar",
    ],
  },

  // Rajshahi Division
  {
    zila: "Bogra",
    upazila: [
      "Adamdighi",
      "Bogra Sadar",
      "Dhunat",
      "Dupchanchia",
      "Gabtali",
      "Kahaloo",
      "Nandigram",
      "Shajahanpur",
      "Sherpur",
      "Shibganj",
      "Sonatala",
      "Sariakandi",
    ],
  },
  {
    zila: "Joypurhat",
    upazila: ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
  },
  {
    zila: "Naogaon",
    upazila: [
      "Atrai",
      "Badalgachhi",
      "Dhamoirhat",
      "Manda",
      "Mohadevpur",
      "Naogaon Sadar",
      "Niamatpur",
      "Patnitala",
      "Porsha",
      "Raninagar",
      "Sapahar",
    ],
  },
  {
    zila: "Natore",
    upazila: [
      "Baraigram",
      "Bagatipara",
      "Lalpur",
      "Natore Sadar",
      "Singra",
      "Gurudaspur",
      "Naldanga",
    ],
  },
  {
    zila: "Nawabganj",
    upazila: [
      "Bholahat",
      "Gomostapur",
      "Nachole",
      "Nawabganj Sadar",
      "Shibganj",
    ],
  },
  {
    zila: "Pabna",
    upazila: [
      "Atgharia",
      "Bera",
      "Bhangura",
      "Chatmohar",
      "Faridpur",
      "Ishwardi",
      "Pabna Sadar",
      "Santhia",
      "Sujanagar",
    ],
  },
  {
    zila: "Rajshahi",
    upazila: [
      "Bagha",
      "Bagmara",
      "Charghat",
      "Durgapur",
      "Godagari",
      "Mohanpur",
      "Paba",
      "Puthia",
      "Tanore",
    ],
  },
  {
    zila: "Sirajganj",
    upazila: [
      "Belkuchi",
      "Chauhali",
      "Kamarkhanda",
      "Kazipur",
      "Raiganj",
      "Shahjadpur",
      "Sirajganj Sadar",
      "Tarash",
      "Ullahpara",
    ],
  },

  // Sylhet Division
  {
    zila: "Habiganj",
    upazila: [
      "Ajmiriganj",
      "Bahubal",
      "Baniachong",
      "Chunarughat",
      "Habiganj Sadar",
      "Lakhai",
      "Madhabpur",
      "Nabiganj",
      "Shaistaganj",
    ],
  },
  {
    zila: "Moulvibazar",
    upazila: [
      "Barlekha",
      "Kamalganj",
      "Kulaura",
      "Moulvibazar Sadar",
      "Rajnagar",
      "Sreemangal",
      "Juri",
    ],
  },
  {
    zila: "Sunamganj",
    upazila: [
      "Bishwamvarpur",
      "Chhatak",
      "Derai",
      "Dharampasha",
      "Dowarabazar",
      "Jagannathpur",
      "Jamalganj",
      "Sadar",
      "Shantiganj",
      "Sullah",
      "Tahirpur",
    ],
  },
  {
    zila: "Sylhet",
    upazila: [
      "Balaganj",
      "Beanibazar",
      "Bishwanath",
      "Companiganj",
      "Dakshin Surma",
      "Fenchuganj",
      "Golapganj",
      "Gowainghat",
      "Jaintiapur",
      "Kanaighat",
      "Sylhet Sadar",
      "Zakiganj",
    ],
  },

  // Rangpur Division
  {
    zila: "Dinajpur",
    upazila: [
      "Birampur",
      "Birganj",
      "Biral",
      "Bochaganj",
      "Chirirbandar",
      "Dinajpur Sadar",
      "Ghoraghat",
      "Hakimpur",
      "Kaharol",
      "Khansama",
      "Nawabganj",
      "Parbatipur",
    ],
  },
  {
    zila: "Gaibandha",
    upazila: [
      "Fulchhari",
      "Gaibandha Sadar",
      "Gobindaganj",
      "Palashbari",
      "Sadullapur",
      "Saghata",
      "Sundarganj",
    ],
  },
  {
    zila: "Kurigram",
    upazila: [
      "Bhurungamari",
      "Char Rajibpur",
      "Chilmari",
      "Kurigram Sadar",
      "Nageshwari",
      "Phulbari",
      "Rajarhat",
      "Raumari",
      "Ulipur",
    ],
  },
  {
    zila: "Lalmonirhat",
    upazila: [
      "Aditmari",
      "Hatibandha",
      "Kaliganj",
      "Lalmonirhat Sadar",
      "Patgram",
    ],
  },
  {
    zila: "Nilphamari",
    upazila: [
      "Dimla",
      "Domar",
      "Jaldhaka",
      "Kishorganj",
      "Nilphamari Sadar",
      "Saidpur",
    ],
  },
  {
    zila: "Panchagarh",
    upazila: ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
  },
  {
    zila: "Rangpur",
    upazila: [
      "Badarganj",
      "Gangachara",
      "Kaunia",
      "Mithapukur",
      "Pirgachha",
      "Pirganj",
      "Rangpur Sadar",
      "Taraganj",
    ],
  },
  {
    zila: "Thakurgaon",
    upazila: [
      "Baliadangi",
      "Haripur",
      "Pirganj",
      "Ranisankail",
      "Thakurgaon Sadar",
    ],
  },

  // Barisal Division
  {
    zila: "Barguna",
    upazila: [
      "Barguna Sadar",
      "Amtali",
      "Betagi",
      "Bamna",
      "Patharghata",
      "Taltali",
    ],
  },
  {
    zila: "Barisal",
    upazila: [
      "Agailjhara",
      "Babuganj",
      "Bakerganj",
      "Banaripara",
      "Gaurnadi",
      "Hizla",
      "Mehendiganj",
      "Muladi",
      "Wazirpur",
      "Barisal Sadar",
    ],
  },
  {
    zila: "Bhola",
    upazila: [
      "Bhola Sadar",
      "Borhanuddin",
      "Char Fasson",
      "Daulatkhan",
      "Lalmohan",
      "Manpura",
      "Tazumuddin",
    ],
  },
  {
    zila: "Jhalokati",
    upazila: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
  },
  {
    zila: "Patuakhali",
    upazila: [
      "Bauphal",
      "Dashmina",
      "Galachipa",
      "Kalapara",
      "Mirzaganj",
      "Patuakhali Sadar",
      "Dumki",
      "Rangabali",
    ],
  },
  {
    zila: "Pirojpur",
    upazila: [
      "Bhandaria",
      "Kaukhali",
      "Mathbaria",
      "Nesarabad",
      "Nazirpur",
      "Pirojpur Sadar",
      "Zianagar",
    ],
  },

  // Khulna Division
  {
    zila: "Bagerhat",
    upazila: [
      "Bagerhat Sadar",
      "Chitalmari",
      "Fakirhat",
      "Kachua",
      "Mollahat",
      "Mongla",
      "Morrelganj",
      "Rampal",
      "Sarankhola",
    ],
  },
  {
    zila: "Chuadanga",
    upazila: ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
  },
  {
    zila: "Jessore",
    upazila: [
      "Abhaynagar",
      "Bagherpara",
      "Chaugachha",
      "Jessore Sadar",
      "Jhikargachha",
      "Keshabpur",
      "Manirampur",
      "Sharsha",
    ],
  },
  {
    zila: "Jhenaidah",
    upazila: [
      "Harinakundu",
      "Jhenaidah Sadar",
      "Kaliganj",
      "Kotchandpur",
      "Moheshpur",
      "Shailkupa",
    ],
  },
  {
    zila: "Khulna",
    upazila: [
      "Batiaghata",
      "Dacope",
      "Dumuria",
      "Dighalia",
      "Koyra",
      "Paikgachha",
      "Phultala",
      "Rupsa",
      "Terokhada",
    ],
  },
  {
    zila: "Kushtia",
    upazila: [
      "Bheramara",
      "Daulatpur",
      "Khoksa",
      "Kumarkhali",
      "Kushtia Sadar",
      "Mirpur",
    ],
  },
  {
    zila: "Magura",
    upazila: ["Magura Sadar", "Mohammadpur", "Salikha", "Sreepur"],
  },
  {
    zila: "Meherpur",
    upazila: ["Meherpur Sadar", "Gangni", "Mujibnagar"],
  },
  {
    zila: "Narail",
    upazila: ["Kalia", "Lohagara", "Narail Sadar"],
  },
  {
    zila: "Satkhira",
    upazila: [
      "Assasuni",
      "Debhata",
      "Kaliganj",
      "Kalaroa",
      "Satkhira Sadar",
      "Shyamnagar",
      "Tala",
    ],
  },

  // Mymensingh Division
  {
    zila: "Jamalpur",
    upazila: [
      "Baksiganj",
      "Dewanganj",
      "Islampur",
      "Jamalpur Sadar",
      "Madarganj",
      "Melandah",
      "Sarishabari",
    ],
  },
  {
    zila: "Mymensingh",
    upazila: [
      "Bhaluka",
      "Dhobaura",
      "Fulbaria",
      "Gaffargaon",
      "Gauripur",
      "Haluaghat",
      "Iswarganj",
      "Muktagachha",
      "Mymensingh Sadar",
      "Nandail",
      "Phulpur",
      "Trishal",
      "Tarakanda",
    ],
  },
  {
    zila: "Netrokona",
    upazila: [
      "Atpara",
      "Barhatta",
      "Durgapur",
      "Kalmakanda",
      "Kendua",
      "Khaliajuri",
      "Madan",
      "Mohanganj",
      "Netrokona Sadar",
      "Purbadhala",
    ],
  },
  {
    zila: "Sherpur",
    upazila: [
      "Jhenaigati",
      "Nalitabari",
      "Nokla",
      "Sherpur Sadar",
      "Sreebardi",
    ],
  },
];
