import Footer from "@/components/layout/Footer";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Bengali, Outfit } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const anekBangla = Noto_Sans_Bengali({
  variable: "--font-anek-bangla",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} ${anekBangla.variable} antialiased bg-bg scroll-container`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
